N = 2

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 3000

  config.vm.define "master" do |master|
    master.vm.box = "jharoian3/ubuntu-22.04-arm64"
    master.vm.box_version = "0.3"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
    master.vm.hostname = "master"

    master.vm.provider "parallels" do |v|
      v.memory = 2048
      v.cpus = 2
    end
    
    master.vm.provision "shell", path: "master_env_build.sh", args: N
  end

  (1..N).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = "jharoian3/ubuntu-22.04-arm64"
      worker.vm.box_version = "0.3"
      worker.vm.network "private_network", ip: "192.168.56.1#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "6001#{i}", auto_correct: true, id: "ssh"
      worker.vm.hostname = "worker#{i}"

      worker.vm.provider "parallels" do |v|
        v.memory = 1024
        v.cpus = 1
      end

      worker.vm.provision "shell", path: "worker_env_build.sh", args: N
    end
  end
end